SPECFEM/specfem2d

- doc/USER_MANUAL/bibliography.bib
- doc/USER_MANUAL/manual_SPECFEM2D.tex
update the bibtex for one reference, which is cited before its publication
> update the bibtex for one reference

- EXAMPLES/Gmsh_example_Stacey_MPI/run_this_example.sh
- EXAMPLES/Gmsh_example_Stacey_serial/run_this_example.sh
- EXAMPLES/LuoYang_fluid_solid_kernel/process_kernel.sh
- EXAMPLES/LuoYang_fluid_solid_kernel/run_this_example.sh
- EXAMPLES/Rayleigh_wave_no_crack/run_this_example.sh
- EXAMPLES/Rayleigh_wave_with_crack/run_this_example.sh
- EXAMPLES/Tape2007/process_checker.sh
- EXAMPLES/Tape2007/run_this_example.sh
- EXAMPLES/Tape2007_kernel/process_kernel.sh
- EXAMPLES/Tape2007_kernel/run_this_example.sh
- EXAMPLES/Tromp2005/run_this_example.sh
- EXAMPLES/Tromp2005_kernel/process_kernel.sh
- EXAMPLES/Tromp2005_kernel/run_this_example.sh
- EXAMPLES/ZZZ_currently_broken_or_obsolete_examples_but_do_not_remove/older_attenuation_with_Carcione_1988_1_over_N_problem/run_this_example.sh
- EXAMPLES/acoustic_poroelastic/run_this_example.sh
- EXAMPLES/attenuation/run_this_example.sh
- EXAMPLES/canyon/run_this_example.sh
- EXAMPLES/fluid_solid/fluid_solid_external_mesh/run_this_example.sh
- EXAMPLES/fluid_solid/from_2000_Geophysics_paper_flat_ocean_bottom/run_this_example.sh
- EXAMPLES/fluid_solid/from_2000_Geophysics_paper_sinusoidal_ocean_bottom/run_this_example.sh
- EXAMPLES/initial_plane_wave/adj.sh
- EXAMPLES/initial_plane_wave/run_for_ker.sh
- EXAMPLES/initial_plane_wave/run_this_example.sh
- EXAMPLES/salt_dome_CUBIT_mesh/CPML_homogeneous/run_this_example.sh
- EXAMPLES/salt_dome_CUBIT_mesh/CPML_normal_fluid_solid/run_this_example.sh
- EXAMPLES/salt_dome_CUBIT_mesh/CPML_normal_solid_only/run_this_example.sh
- EXAMPLES/salt_dome_CUBIT_mesh/Stacey_homogeneous/run_this_example.sh
- EXAMPLES/salt_dome_CUBIT_mesh/Stacey_normal_fluid_solid/run_this_example.sh
- EXAMPLES/thermocline/run_this_example.sh
Changed echo `date` to date which is actually the same
> Replaced echo `date` to date which is actually the same

- UTILS/cubit2specfem2d/cubit2specfem2d.py
New version of cubit2specfem2d.py including axisymmetric 2D meshes
> New version of cubit2specfem2d.py including axisymmetric 2D meshes

- EXAMPLES/Tape2007/Par_file_Tape2007_132rec_checker
- EXAMPLES/Tape2007/process_checker.sh
- UTILS/cubit2specfem2d/cubit2specfem2d.py
Some changes especially  on cubit2specfem2d
> Some changes especially  on cubit2specfem2d

- utils/cubit2specfem2d/README
- utils/cubit2specfem2d/cubit2specfem2d.py
- utils/cubit2specfem2d/simpleAxisym2dMesh.py
Add a first example of 2.5D external mesh export
> Add a first example of 2.5D external mesh export 

- utils/cubit2specfem2d/cubit2specfem2d.py
- utils/cubit2specfem2d/simpleAxisym2dMesh.py
> Clean axisym mesh example

- src/specfem2D/compute_coupling_acoustic_el.f90
- src/specfem2D/compute_forces_viscoelastic.F90
- src/specfem2D/compute_forces_viscoelastic_backward.F90
- src/specfem2D/iterate_time.F90
- src/specfem2D/prepare_timerun.F90
- src/specfem2D/prepare_timerun_body.F90
- src/specfem2D/specfem2D.F90
Really hard for me to find, two whole days.
>  fix the error that the output file index of rhop_alpha_beta_kernel and rho_kappa_mu_kernel changed

- EXAMPLES/LuoYang_fluid_solid_kernel/compare_two_images_to_compare_sensitivity_kernels.py
Some minor tweaks to the kernel comparison script. Add Python 3 compatibility, remove OpenCV dependency, and simplify some stuff.
> Kernel comparison script updates

- src/specfem2D/rules.mk
See build error in #427.
cc, @luet.
> Fix typo in dependency rule breaking parallel builds.

- src/cuda/compute_forces_acoustic_cuda.cu
- src/cuda/update_displacement_cuda.cu
- src/specfem2D/acoustic_cuda.f90
- src/specfem2D/iterate_time.F90
Summary :
- Correct a bug in kernel calculation (now compute rhop_kernel and alpha_kernel)
- Enhancement of GPU mode, improving the arithmetic intensity for adjoint simulations, and reducing global memory acces in the Newmark scheme.
> Enhancements in GPU mode

- src/cuda/compute_forces_acoustic_cuda.cu
- src/cuda/update_displacement_cuda.cu
- Corrected bug introduced by previous commit.
- Enhancement of GPU version, reducing the dimension of the thread, leading up to a 20% speedup.
> Correct bug in GPU mode

- EXAMPLES/axisymmetric_case_AXISYM_option/README
- EXAMPLES/axisymmetric_case_AXISYM_option/run_this_example.sh
- src/specfem2D/check_grid.F90
- src/specfem2D/setup_sources_receivers.F90
files moved to OUTPUT_FILES/ directory:
- plot_points_per_wavelength_histogram.gnu 
- points_per_wavelength_histogram_* 
- for_information_SOURCE_actually_used  
- for_information_STATIONS_actually_used
> outputs plot & info files into directory OUTPUT_FILES/

- src/specfem2D/rules.mk
- src/tomography/postprocess_sensitivity_kernels/rules.mk
-Fix broken dependency rule
-Fix output message
> Small Update Makefile

- src/meshfem2D/rules.mk
Fixes #515, #516, #517, #518, #519.
> Fix build dependency for scotch.

- src/specfem2D/assemble_MPI.F90
- src/specfem2D/compute_add_sources_poro.f90
- src/specfem2D/compute_add_sources_viscoelastic.f90
- src/specfem2D/compute_forces_acoustic.f90
- src/specfem2D/compute_forces_acoustic_backward.f90
- src/specfem2D/compute_forces_acoustic_calling_routine.F90
- src/specfem2D/compute_forces_poro_fluid.f90
- src/specfem2D/compute_forces_poro_solid.f90
- src/specfem2D/compute_forces_poroelastic_calling_routine.F90
- src/specfem2D/compute_forces_viscoelastic.F90
- src/specfem2D/compute_forces_viscoelastic_backward.F90
- src/specfem2D/compute_forces_viscoelastic_calling_routine.F90
- src/specfem2D/compute_stacey_acoustic.f90
- src/specfem2D/compute_stacey_elastic.f90
- src/specfem2D/compute_stacey_poroelastic.f90
- src/specfem2D/pml_compute.f90
- src/specfem2D/prepare_assemble_MPI.F90
- src/specfem2D/read_external_model.f90
- src/specfem2D/rules.mk
simplifies poroelastic source contribution routines
> moves stacey boundaries routines into separate files

- utils/cubit2specfem2d/cubit2specfem2d.py
> Add a new functionnality to cubit2specfem2d.py (several acoustic or elastic

- src/specfem2D/prepare_timerun.F90
- src/specfem2D/read_mesh_databases.F90
- src/specfem2D/setup_mesh.F90
> Fix some bugs for the use of external velocity models that have been

- utils/cubit2specfem2d/cubit2specfem2d_QUAD9.py
> Some modifications to that script in order to prepare a possible future merge

- src/meshfem2D/rules.mk
> Add missing deps for compute_elements_load_par module.

- src/meshfem2D/read_material_table.f90
- src/meshfem2D/read_parameter_file.F90
- src/shared/parallel.F90
It was just a variable that was allocated twice
> Fix a the code that was broken by the last commit

- src/meshfem2D/meshfem2D.F90
- src/shared/parallel.F90
- src/shared/read_value_parameters.f90
Now I have to remove some spurious comments and I am completely done
> Fix last bugs for NUMBER_OF_SIMULATANEOUS_RUNS... now it works! 

- src/specfem2D/compute_attenuation_viscoelastic.f90
- src/specfem2D/compute_forces_viscoelastic.F90
- src/specfem2D/compute_forces_viscoelastic_calling_routine.F90
- src/specfem2D/iterate_time_undoatt.F90
- src/specfem2D/pml_compute_memory_variables.f90
- src/specfem2D/prepare_timerun.F90
- src/specfem2D/specfem2D_par.f90
Also, some code factorization in the compute_forces. 
Right now, the compute_gradient_attenuation routines are not used anymore, we can suppress this file.
> Enhanced performances for viscoelastic simulations

- src/cuda/compute_add_sources_viscoacoustic_cuda.cu
- src/cuda/compute_add_sources_viscoelastic_cuda.cu
- src/cuda/compute_coupling_cuda.cu
- src/cuda/compute_forces_acoustic_cuda.cu
- src/cuda/compute_kernels_cuda.cu
- src/cuda/compute_stacey_acoustic_cuda.cu
- src/cuda/compute_stacey_viscoelastic_cuda.cu
- src/cuda/mesh_constants_cuda.h
- src/cuda/prepare_mesh_constants_cuda.cu
- src/cuda/specfem2D_gpu_cuda_method_stubs.c
- src/cuda/transfer_fields_cuda.cu
- src/cuda/update_displacement_cuda.cu
- src/specfem2D/compute_gpu_acoustic.f90
- src/specfem2D/compute_kernels.f90
- src/specfem2D/finalize_simulation.F90
- src/specfem2D/initialize_simulation.F90
- src/specfem2D/iterate_time.F90
- src/specfem2D/iterate_time_undoatt.F90
- src/specfem2D/prepare_gpu.f90
- src/specfem2D/prepare_timerun.F90
- src/specfem2D/read_forward_arrays.f90
- src/specfem2D/save_read_array_for_undoatt.f90
- src/specfem2D/specfem2D_par.f90
- src/specfem2D/update_displacement_Newmark.F90
- src/specfem2D/write_color_image_snaphot.F90
- src/specfem2D/write_movie_output.f90
- A double level of asynchronous I/O is implemented, to overlap both GPU==>RAM and RAM==> disk transfers, for the acoustic case.
- The GPU code is also improved, with some unnecessary synchronizations removed.
- The GPU is now compatible with NGLLX /= 5.
> Added GPU support in acoustics for NO_BACKWARD_RECONSTRUCTION option

- README.md
Same PR as geodynamics/specfem3d#1525, but for SPECFEM2D.
> Update README for contributions and authors

- EXAMPLES/Marmousi_mesh_of_the_model/improved_mesh_from_Hom_Nath_Gharti_2023_using_CUBIT_higher_resolution/README_higher_resolution_Marmousi_mesh_from_Hom_Nath_Gharti.txt
This fixes the negative Jacobian issue.
> - replaced old Marmousi mesh files with new mesh file.
